version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
