#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Services\Boot;
use Symfony\Component\Console\Application;

require __DIR__ . '/app/predefine.php';
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/.config.php';
require __DIR__ . '/app/envload.php';

Boot::setTime();
Boot::bootSentry();
Boot::bootDb();

$application = new Application();

// ... register commands

$application->run();
