ALTER TABLE `bought` ADD `is_renewed` BOOLEAN NOT NULL DEFAULT FALSE AFTER `price`;
ALTER TABLE `ss_node` ADD` online` BOOLEAN NOT NULL DEFAULT FALSE AFTER `mu_only`
    ,ADD `gfw_block` BOOLEAN NOT NULL DEFAULT FALSE AFTER `online`;
ALTER TABLE `user` ADD `expired` BOOLEAN NOT NULL DEFAULT FALSE AFTER `telegram_id`
    ,ADD `traffic_notified` BOOLEAN NULL DEFAULT FALSE AFTER `expired`;
