name: Lint code
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      
      - run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require nunomaduro/phpinsights
          composer clearcache -q
          vendor/bin/phpinsights --version
          vendor/bin/phpinsights --no-interaction --format=github-action --min-style=100 --min-architecture=100 --min-quality=100
